version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - crackhash_net
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh admin -u admin -p pass --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8081:8081"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - crackhash_net
    restart: always

  manager:
    container_name: manager
    build: ./manager
    ports:
      - "3000:3000"
    networks:
      - crackhash_net
    depends_on:
      - worker1
      - worker2
      - worker3
      - mongo

  worker1:
    build: ./worker
    environment:
      - WORKER_NAME=worker1
    networks:
      - crackhash_net

  worker2:
    build: ./worker
    environment:
      - WORKER_NAME=worker2
    networks:
      - crackhash_net

  worker3:
    build: ./worker
    environment:
      - WORKER_NAME=worker3
    networks:
      - crackhash_net

volumes:
  mongo_data:

networks:
  crackhash_net:
    driver: bridge